/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as QuotationPublicIdRouteImport } from './routes/quotation-public/$id'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardQuotationsIndexRouteImport } from './routes/dashboard/quotations/index'
import { Route as DashboardQuotationsCreateRouteImport } from './routes/dashboard/quotations/create'
import { Route as DashboardQuotationsIdIndexRouteImport } from './routes/dashboard/quotations/$id/index'
import { Route as DashboardQuotationsIdEditRouteImport } from './routes/dashboard/quotations/$id/edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationPublicIdRoute = QuotationPublicIdRouteImport.update({
  id: '/quotation-public/$id',
  path: '/quotation-public/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardQuotationsIndexRoute =
  DashboardQuotationsIndexRouteImport.update({
    id: '/dashboard/quotations/',
    path: '/dashboard/quotations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardQuotationsCreateRoute =
  DashboardQuotationsCreateRouteImport.update({
    id: '/dashboard/quotations/create',
    path: '/dashboard/quotations/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardQuotationsIdIndexRoute =
  DashboardQuotationsIdIndexRouteImport.update({
    id: '/dashboard/quotations/$id/',
    path: '/dashboard/quotations/$id/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardQuotationsIdEditRoute =
  DashboardQuotationsIdEditRouteImport.update({
    id: '/dashboard/quotations/$id/edit',
    path: '/dashboard/quotations/$id/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/quotation-public/$id': typeof QuotationPublicIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/quotations/create': typeof DashboardQuotationsCreateRoute
  '/dashboard/quotations': typeof DashboardQuotationsIndexRoute
  '/dashboard/quotations/$id/edit': typeof DashboardQuotationsIdEditRoute
  '/dashboard/quotations/$id': typeof DashboardQuotationsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/quotation-public/$id': typeof QuotationPublicIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/quotations/create': typeof DashboardQuotationsCreateRoute
  '/dashboard/quotations': typeof DashboardQuotationsIndexRoute
  '/dashboard/quotations/$id/edit': typeof DashboardQuotationsIdEditRoute
  '/dashboard/quotations/$id': typeof DashboardQuotationsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/quotation-public/$id': typeof QuotationPublicIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/quotations/create': typeof DashboardQuotationsCreateRoute
  '/dashboard/quotations/': typeof DashboardQuotationsIndexRoute
  '/dashboard/quotations/$id/edit': typeof DashboardQuotationsIdEditRoute
  '/dashboard/quotations/$id/': typeof DashboardQuotationsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard/settings'
    | '/quotation-public/$id'
    | '/dashboard'
    | '/dashboard/quotations/create'
    | '/dashboard/quotations'
    | '/dashboard/quotations/$id/edit'
    | '/dashboard/quotations/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard/settings'
    | '/quotation-public/$id'
    | '/dashboard'
    | '/dashboard/quotations/create'
    | '/dashboard/quotations'
    | '/dashboard/quotations/$id/edit'
    | '/dashboard/quotations/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/dashboard/settings'
    | '/quotation-public/$id'
    | '/dashboard/'
    | '/dashboard/quotations/create'
    | '/dashboard/quotations/'
    | '/dashboard/quotations/$id/edit'
    | '/dashboard/quotations/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  QuotationPublicIdRoute: typeof QuotationPublicIdRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardQuotationsCreateRoute: typeof DashboardQuotationsCreateRoute
  DashboardQuotationsIndexRoute: typeof DashboardQuotationsIndexRoute
  DashboardQuotationsIdEditRoute: typeof DashboardQuotationsIdEditRoute
  DashboardQuotationsIdIndexRoute: typeof DashboardQuotationsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotation-public/$id': {
      id: '/quotation-public/$id'
      path: '/quotation-public/$id'
      fullPath: '/quotation-public/$id'
      preLoaderRoute: typeof QuotationPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/quotations/': {
      id: '/dashboard/quotations/'
      path: '/dashboard/quotations'
      fullPath: '/dashboard/quotations'
      preLoaderRoute: typeof DashboardQuotationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/quotations/create': {
      id: '/dashboard/quotations/create'
      path: '/dashboard/quotations/create'
      fullPath: '/dashboard/quotations/create'
      preLoaderRoute: typeof DashboardQuotationsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/quotations/$id/': {
      id: '/dashboard/quotations/$id/'
      path: '/dashboard/quotations/$id'
      fullPath: '/dashboard/quotations/$id'
      preLoaderRoute: typeof DashboardQuotationsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/quotations/$id/edit': {
      id: '/dashboard/quotations/$id/edit'
      path: '/dashboard/quotations/$id/edit'
      fullPath: '/dashboard/quotations/$id/edit'
      preLoaderRoute: typeof DashboardQuotationsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  QuotationPublicIdRoute: QuotationPublicIdRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardQuotationsCreateRoute: DashboardQuotationsCreateRoute,
  DashboardQuotationsIndexRoute: DashboardQuotationsIndexRoute,
  DashboardQuotationsIdEditRoute: DashboardQuotationsIdEditRoute,
  DashboardQuotationsIdIndexRoute: DashboardQuotationsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
